title: "DataFun - ERP"
description: "Sistema web de gestión ERP"
baseurl: "/datafun"
url: "https://liosdany-rivero.github.io"
theme: jekyll-theme-cayman
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Configuración de navegación
nav_order:
  - index.md
  - caracteristicas/Accesos_Niveles.md
