title: "DataFun - ERP"
description: "Sistema web de gestión ERP"
baseurl: "/datafun"
url: "https://liosdany-rivero.github.io"

# Tema Just the Docs
remote_theme: just-the-docs/just-the-docs

# Configuración básica
lang: es
search_enabled: true

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Configuración de Just the Docs
aux_links:
  "Repositorio GitHub": "https://github.com/liosdany-rivero/datafun"

# Color scheme dark
color_scheme: dark

# Heading anchors
heading_anchors: true

# Callouts
callbacks_level: quiet

# Navegación
nav_external_links:
  - title: "GitHub Repo"
    url: "https://github.com/liosdany-rivero/datafun"

# Colecciones
collections:
  docs:
    permalink: "/:path/"
    output: true

# Configuración por defecto
defaults:
  - scope:
      path: ""
      type: docs
    values:
      layout: default
      search: true
      toc: true