title: "DataFun - ERP"
description: "Sistema web de gestión ERP"
baseurl: "/datafun"
url: "https://liosdany-rivero.github.io"
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Configuración de navegación
nav_order:
  - index.md
  - sistema-accesos/accesos-roles.md
  - sistema-accesos/accesos-niveles.md
