title: "DataFun - ERP"
description: "Sistema web de gestión ERP"
baseurl: "/datafun"
url: "http://localhost:4000"

# Tema para desarrollo local
theme: just-the-docs

# Configuración básica
lang: "es"
search_enabled: true

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Configuración de Just the Docs
aux_links:
  "Repositorio GitHub": "https://github.com/liosdany-rivero/datafun"

color_scheme: "dark"
heading_anchors: true

# Navegación
nav_external_links:
  - title: "GitHub Repo"
    url: "https://github.com/liosdany-rivero/datafun"

# Colecciones
collections:
  docs:
    permalink: "/:path/"
    output: true

# Configuración por defecto
defaults:
  - scope:
      path: ""
      type: docs
    values:
      layout: "default"
      search: true
      toc: true
