title: "DataFun - ERP"
description: "Sistema web de gesti√≥n ERP"
baseurl: "/datafun"
url: "https://liosdany-rivero.github.io"
theme: jekyll-theme-cayman
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

nav_order:
  - 00index.md
  - instalacion.md
  - estructura.md
  - modulos.md
  - api.md
  - desarrollo.md
